on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      # So `git describe` works on forked branches:
      - run: git remote add upstream https://github.com/mongodb/mongo-tools
      - run: git fetch upstream --prune --unshallow --tags

      - run: ./make test:unit
